const OrderStatusType = {
  ORDER_PAYMENT_PENDING: 'ORDER_PAYMENT_PENDING',
  ORDER_PAYMENT_CONFIRMING: 'ORDER_PAYMENT_CONFIRMING',
  ORDER_PAYMENT_COMPLETED: 'ORDER_PAYMENT_COMPLETED',
  ORDER_PAYMENT_LACK: 'ORDER_PAYMENT_LACK',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_FAIL: 'ORDER_FAIL',
}

const PaymentStatusType = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  LACK: 'LACK',
}

export { OrderStatusType, PaymentStatusType }
